[performance]
par = 1
dbcache = 1536
blocksonly = 1
maxuploadtarget = 137
mempoolexpiry = 72
maxmempool = 300
maxorphantx = 100

[spam_protection]
limitfreerelay = 10
minrelaytxfee = 0.0001

[connections]
maxconnections = 32

[civkitd]
network = "testnet"
noise_port = 9735
nostr_port = 9736
cli_port = 9737
clientmustpaypublication = 1