[performance]
max_db_size = 10000
max_event_age = 3600

[spam_protection]
requestcredentials = true

[connections]
maxclientconnections = 100

[civkitd]
network = "testnet"
noise_port = 9735
nostr_port = 50021
cli_port = 50031

[logging]
level = "info"

[mainstay]
url = "https://mainstay.xyz/api/v1"
position = 0
token = "14b2b754-5806-4157-883c-732baf88849c"
base_pubkey = "038695a7bf3a49d951d7e71bb0ca54158ca1a020e209653706c0dcad344f9b9d05"
chain_code = "14df7ece79e83f0f479a37832d770294014edc6884b0c8bfa2e0aaf51fb00229"

[bitcoind_params]
host = "https://127.0.0.1"
port = "18443"
rpc_user = "civkitd_client"
rpc_password = "hello_world"
# can be "bitcoin" or "testnet"
chain = "testnet"
